Update Aufgabe1.py
Update by Marco Kroll

noch nicht Funktionsfähig
bekomme Meldung
Traceback (most recent call last):
  File "/Users/marcokroll/Documents/GitHub/Aufgabe 1/main.py", line 18, in <module>
    ID, Vorname, Name, Strasse, Hausnr, PLZ, Ort, Telefon = row
ValueError: not enough values to unpack (expected 8, got 1)